spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411/

exchange:
  movie:
    name: movieExchange

queue:
  movie:
    name: MovieQueue

  serie:
    name: SerieQueue